# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DepthInfo.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'DepthInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x44\x65pthInfo.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\xf6\x01\n\tDepthInfo\x12\x13\n\x0b\x64\x65pth_topic\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x12\x12\n\ntimestamps\x18\x05 \x03(\x04\x12\t\n\x01K\x18\x06 \x03(\x01\x12\n\n\x02xi\x18\x07 \x01(\x01\x12\r\n\x05\x61lpha\x18\x08 \x01(\x01\x12\r\n\x05\x63odec\x18\t \x01(\t\x12\r\n\x05\x64type\x18\n \x01(\t\x12+\n\x06header\x18\x0b \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12!\n\x0csequence_num\x18\x0c \x01(\rR\x0bsequenceNumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DepthInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPTHINFO']._serialized_start=44
  _globals['_DEPTHINFO']._serialized_end=290
# @@protoc_insertion_point(module_scope)
