# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FrameValidity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'FrameValidity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x46rameValidity.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"-\n\x0c\x46rameFailure\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xb6\x01\n\rFrameValidity\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x11\n\tref_topic\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x04\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\x12(\n\x08\x66\x61ilures\x18\x05 \x03(\x0b\x32\x16.foxglove.FrameFailure\x12\x13\n\x0b\x66rame_index\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FrameValidity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEFAILURE']._serialized_start=47
  _globals['_FRAMEFAILURE']._serialized_end=92
  _globals['_FRAMEVALIDITY']._serialized_start=95
  _globals['_FRAMEVALIDITY']._serialized_end=277
# @@protoc_insertion_point(module_scope)
