# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HandTrackInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2
import header_pb2 as header__pb2
import Vector3_pb2 as Vector3__pb2
import Quaternion_pb2 as Quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='HandTrackInfo.proto',
  package='foxglove',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13HandTrackInfo.proto\x12\x08\x66oxglove\x1a\x0b\x43olor.proto\x1a\x0cheader.proto\x1a\rVector3.proto\x1a\x10Quaternion.proto\"\xee\x01\n\x15HandPointToParentInfo\x12#\n\x08position\x18\x01 \x01(\x0b\x32\x11.foxglove.Vector3\x12)\n\x0borientation\x18\x02 \x01(\x0b\x32\x14.foxglove.Quaternion\x12\'\n\x0c\x65uler_angles\x18\x03 \x01(\x0b\x32\x11.foxglove.Vector3\x12+\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x11.foxglove.Vector3\x12/\n\x14\x61ngular_acceleration\x18\x05 \x01(\x0b\x32\x11.foxglove.Vector3\"\xb5\x01\n\x15HandPointToGlobalInfo\x12#\n\x08position\x18\x01 \x01(\x0b\x32\x11.foxglove.Vector3\x12#\n\x08velocity\x18\x02 \x01(\x0b\x32\x11.foxglove.Vector3\x12\'\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x0b\x32\x11.foxglove.Vector3\x12)\n\x0borientation\x18\x04 \x01(\x0b\x32\x14.foxglove.Quaternion\"\xae\x01\n\rHandPointInfo\x12\x11\n\tbone_name\x18\x01 \x01(\t\x12\x32\n\tto_parent\x18\x02 \x01(\x0b\x32\x1f.foxglove.HandPointToParentInfo\x12\x32\n\tto_global\x18\x03 \x01(\x0b\x32\x1f.foxglove.HandPointToGlobalInfo\x12\x16\n\x0esegment_length\x18\x04 \x01(\x01\x12\n\n\x02id\x18\x05 \x01(\x05\"\x9f\x01\n\x12HandPointFrameInfo\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12*\n\tbone_data\x18\x02 \x03(\x0b\x32\x17.foxglove.HandPointInfo\x12\x10\n\x08is_valid\x18\x03 \x01(\x08\x12\x1e\n\x05\x63olor\x18\x04 \x01(\x0b\x32\x0f.foxglove.Color\"9\n\x14SegmentHierarchyNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bparent_name\x18\x02 \x01(\t\"\x87\x02\n\rHandTrackInfo\x12,\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x1c.foxglove.HandPointFrameInfo\x12\x12\n\nnum_frames\x18\x02 \x01(\x05\x12\x14\n\x0cnum_segments\x18\x03 \x01(\x05\x12\x17\n\x0f\x64\x61ta_frame_rate\x18\x04 \x01(\x05\x12\x1c\n\x14\x65uler_rotation_order\x18\x05 \x01(\t\x12\x11\n\tbone_axis\x18\x06 \x01(\t\x12\x19\n\x11translation_units\x18\x07 \x01(\t\x12\x39\n\x11segment_hierarchy\x18\x08 \x03(\x0b\x32\x1e.foxglove.SegmentHierarchyNodeb\x06proto3')
  ,
  dependencies=[Color__pb2.DESCRIPTOR,header__pb2.DESCRIPTOR,Vector3__pb2.DESCRIPTOR,Quaternion__pb2.DESCRIPTOR,])




_HANDPOINTTOPARENTINFO = _descriptor.Descriptor(
  name='HandPointToParentInfo',
  full_name='foxglove.HandPointToParentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='foxglove.HandPointToParentInfo.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='foxglove.HandPointToParentInfo.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='euler_angles', full_name='foxglove.HandPointToParentInfo.euler_angles', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='foxglove.HandPointToParentInfo.angular_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_acceleration', full_name='foxglove.HandPointToParentInfo.angular_acceleration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=332,
)


_HANDPOINTTOGLOBALINFO = _descriptor.Descriptor(
  name='HandPointToGlobalInfo',
  full_name='foxglove.HandPointToGlobalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='foxglove.HandPointToGlobalInfo.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='foxglove.HandPointToGlobalInfo.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='foxglove.HandPointToGlobalInfo.acceleration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='foxglove.HandPointToGlobalInfo.orientation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=516,
)


_HANDPOINTINFO = _descriptor.Descriptor(
  name='HandPointInfo',
  full_name='foxglove.HandPointInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bone_name', full_name='foxglove.HandPointInfo.bone_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_parent', full_name='foxglove.HandPointInfo.to_parent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_global', full_name='foxglove.HandPointInfo.to_global', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_length', full_name='foxglove.HandPointInfo.segment_length', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='foxglove.HandPointInfo.id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=693,
)


_HANDPOINTFRAMEINFO = _descriptor.Descriptor(
  name='HandPointFrameInfo',
  full_name='foxglove.HandPointFrameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='foxglove.HandPointFrameInfo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bone_data', full_name='foxglove.HandPointFrameInfo.bone_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='foxglove.HandPointFrameInfo.is_valid', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='foxglove.HandPointFrameInfo.color', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=696,
  serialized_end=855,
)


_SEGMENTHIERARCHYNODE = _descriptor.Descriptor(
  name='SegmentHierarchyNode',
  full_name='foxglove.SegmentHierarchyNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='foxglove.SegmentHierarchyNode.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_name', full_name='foxglove.SegmentHierarchyNode.parent_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=857,
  serialized_end=914,
)


_HANDTRACKINFO = _descriptor.Descriptor(
  name='HandTrackInfo',
  full_name='foxglove.HandTrackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='foxglove.HandTrackInfo.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_frames', full_name='foxglove.HandTrackInfo.num_frames', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_segments', full_name='foxglove.HandTrackInfo.num_segments', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_frame_rate', full_name='foxglove.HandTrackInfo.data_frame_rate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='euler_rotation_order', full_name='foxglove.HandTrackInfo.euler_rotation_order', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bone_axis', full_name='foxglove.HandTrackInfo.bone_axis', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation_units', full_name='foxglove.HandTrackInfo.translation_units', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_hierarchy', full_name='foxglove.HandTrackInfo.segment_hierarchy', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=917,
  serialized_end=1180,
)

_HANDPOINTTOPARENTINFO.fields_by_name['position'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOPARENTINFO.fields_by_name['orientation'].message_type = Quaternion__pb2._QUATERNION
_HANDPOINTTOPARENTINFO.fields_by_name['euler_angles'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOPARENTINFO.fields_by_name['angular_velocity'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOPARENTINFO.fields_by_name['angular_acceleration'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOGLOBALINFO.fields_by_name['position'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOGLOBALINFO.fields_by_name['velocity'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOGLOBALINFO.fields_by_name['acceleration'].message_type = Vector3__pb2._VECTOR3
_HANDPOINTTOGLOBALINFO.fields_by_name['orientation'].message_type = Quaternion__pb2._QUATERNION
_HANDPOINTINFO.fields_by_name['to_parent'].message_type = _HANDPOINTTOPARENTINFO
_HANDPOINTINFO.fields_by_name['to_global'].message_type = _HANDPOINTTOGLOBALINFO
_HANDPOINTFRAMEINFO.fields_by_name['header'].message_type = header__pb2._HEADER
_HANDPOINTFRAMEINFO.fields_by_name['bone_data'].message_type = _HANDPOINTINFO
_HANDPOINTFRAMEINFO.fields_by_name['color'].message_type = Color__pb2._COLOR
_HANDTRACKINFO.fields_by_name['frames'].message_type = _HANDPOINTFRAMEINFO
_HANDTRACKINFO.fields_by_name['segment_hierarchy'].message_type = _SEGMENTHIERARCHYNODE
DESCRIPTOR.message_types_by_name['HandPointToParentInfo'] = _HANDPOINTTOPARENTINFO
DESCRIPTOR.message_types_by_name['HandPointToGlobalInfo'] = _HANDPOINTTOGLOBALINFO
DESCRIPTOR.message_types_by_name['HandPointInfo'] = _HANDPOINTINFO
DESCRIPTOR.message_types_by_name['HandPointFrameInfo'] = _HANDPOINTFRAMEINFO
DESCRIPTOR.message_types_by_name['SegmentHierarchyNode'] = _SEGMENTHIERARCHYNODE
DESCRIPTOR.message_types_by_name['HandTrackInfo'] = _HANDTRACKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandPointToParentInfo = _reflection.GeneratedProtocolMessageType('HandPointToParentInfo', (_message.Message,), dict(
  DESCRIPTOR = _HANDPOINTTOPARENTINFO,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.HandPointToParentInfo)
  ))
_sym_db.RegisterMessage(HandPointToParentInfo)

HandPointToGlobalInfo = _reflection.GeneratedProtocolMessageType('HandPointToGlobalInfo', (_message.Message,), dict(
  DESCRIPTOR = _HANDPOINTTOGLOBALINFO,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.HandPointToGlobalInfo)
  ))
_sym_db.RegisterMessage(HandPointToGlobalInfo)

HandPointInfo = _reflection.GeneratedProtocolMessageType('HandPointInfo', (_message.Message,), dict(
  DESCRIPTOR = _HANDPOINTINFO,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.HandPointInfo)
  ))
_sym_db.RegisterMessage(HandPointInfo)

HandPointFrameInfo = _reflection.GeneratedProtocolMessageType('HandPointFrameInfo', (_message.Message,), dict(
  DESCRIPTOR = _HANDPOINTFRAMEINFO,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.HandPointFrameInfo)
  ))
_sym_db.RegisterMessage(HandPointFrameInfo)

SegmentHierarchyNode = _reflection.GeneratedProtocolMessageType('SegmentHierarchyNode', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTHIERARCHYNODE,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.SegmentHierarchyNode)
  ))
_sym_db.RegisterMessage(SegmentHierarchyNode)

HandTrackInfo = _reflection.GeneratedProtocolMessageType('HandTrackInfo', (_message.Message,), dict(
  DESCRIPTOR = _HANDTRACKINFO,
  __module__ = 'HandTrackInfo_pb2'
  # @@protoc_insertion_point(class_scope:foxglove.HandTrackInfo)
  ))
_sym_db.RegisterMessage(HandTrackInfo)


# @@protoc_insertion_point(module_scope)
