# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StereoCalibration.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'StereoCalibration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17StereoCalibration.proto\x12\x08\x66oxglove\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cheader.proto\"\x93\x03\n\x11StereoCalibration\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fleft_camera_idx\x18\x02 \x01(\x07\x12\x18\n\x10right_camera_idx\x18\x03 \x01(\x07\x12\r\n\x05width\x18\x04 \x01(\x07\x12\x0e\n\x06height\x18\x05 \x01(\x07\x12\x15\n\rleft_frame_id\x18\x06 \x01(\t\x12\x16\n\x0eright_frame_id\x18\x07 \x01(\t\x12\t\n\x01K\x18\x08 \x03(\x01\x12\x0e\n\x06R_left\x18\t \x03(\x01\x12\x0e\n\x06P_left\x18\n \x03(\x01\x12\x0f\n\x07R_right\x18\x0b \x03(\x01\x12\x0f\n\x07P_right\x18\x0c \x03(\x01\x12\t\n\x01T\x18\r \x03(\x01\x12\x12\n\nbaseline_m\x18\x0e \x01(\x01\x12\x12\n\nT_b_c_left\x18\x0f \x03(\x01\x12+\n\x06header\x18\x10 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12!\n\x0csequence_num\x18\x11 \x01(\rR\x0bsequenceNumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StereoCalibration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEREOCALIBRATION']._serialized_start=85
  _globals['_STEREOCALIBRATION']._serialized_end=488
# @@protoc_insertion_point(module_scope)
