# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SystemInfo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'SystemInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SystemInfo.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\xd2\x05\n\nSystemInfo\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x03\x12\x11\n\tmemory_kb\x18\x04 \x01(\x04\x12\x0e\n\x06rss_kb\x18\x05 \x01(\x04\x12\x13\n\x0b\x63pu_percent\x18\x06 \x01(\x02\x12\x16\n\x0ememory_percent\x18\x07 \x01(\x02\x12\x1d\n\x15io_read_bytes_per_sec\x18\x08 \x01(\x04\x12\x1e\n\x16io_write_bytes_per_sec\x18\t \x01(\x04\x12\x0f\n\x07version\x18\n \x01(\t\x12\x18\n\x10product_model_id\x18\x0b \x01(\r\x12\x17\n\x0fHardwareVersion\x18\x0c \x01(\t\x12\x13\n\x0bVersionName\x18\r \x01(\t\x12\x0c\n\x04uuid\x18\x0e \x01(\t\x12\x14\n\x0c\x61\x65s_gcm_salt\x18\x0f \x01(\t\x12K\n\x17recording_start_trigger\x18\x10 \x01(\x0e\x32*.foxglove.SystemInfo.RecordingStartTrigger\x12\x17\n\x0f\x61\x62normal_reason\x18\x11 \x01(\r\"\x85\x02\n\x15RecordingStartTrigger\x12\'\n#RECORDING_START_TRIGGER_UNSPECIFIED\x10\x00\x12\"\n\x1eRECORDING_START_TRIGGER_BUTTON\x10\x01\x12/\n+RECORDING_START_TRIGGER_FINGER_TRIPLE_CLICK\x10\x02\x12%\n!RECORDING_START_TRIGGER_BLUETOOTH\x10\x03\x12\'\n#RECORDING_START_TRIGGER_RF_FOLLOWER\x10\x04\x12\x1e\n\x1aRECORDING_START_TRIGGER_GT\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SystemInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMINFO']._serialized_start=45
  _globals['_SYSTEMINFO']._serialized_end=767
  _globals['_SYSTEMINFO_RECORDINGSTARTTRIGGER']._serialized_start=506
  _globals['_SYSTEMINFO_RECORDINGSTARTTRIGGER']._serialized_end=767
# @@protoc_insertion_point(module_scope)
