# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TimeRangeValidity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'TimeRangeValidity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17TimeRangeValidity.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\x81\x01\n\rValidityRange\x12\x14\n\x0cstart_time_s\x18\x01 \x01(\x01\x12\x12\n\nend_time_s\x18\x02 \x01(\x01\x12\x10\n\x08is_valid\x18\x03 \x01(\x08\x12\x1a\n\x12start_timestamp_ns\x18\x04 \x01(\x04\x12\x18\n\x10\x65nd_timestamp_ns\x18\x05 \x01(\x04\"\xa3\x01\n\x12InvalidRangeDetail\x12\x14\n\x0cstart_time_s\x18\x01 \x01(\x01\x12\x12\n\nend_time_s\x18\x02 \x01(\x01\x12\x1a\n\x12start_timestamp_ns\x18\x03 \x01(\x04\x12\x18\n\x10\x65nd_timestamp_ns\x18\x04 \x01(\x04\x12\x14\n\x0cinvalid_code\x18\x05 \x01(\t\x12\x17\n\x0finvalid_message\x18\x06 \x01(\t\"\x9f\x01\n\x11TimeRangeValidity\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\'\n\x06ranges\x18\x02 \x03(\x0b\x32\x17.foxglove.ValidityRange\x12\x34\n\x0einvalid_ranges\x18\x03 \x03(\x0b\x32\x1c.foxglove.InvalidRangeDetailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TimeRangeValidity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDITYRANGE']._serialized_start=52
  _globals['_VALIDITYRANGE']._serialized_end=181
  _globals['_INVALIDRANGEDETAIL']._serialized_start=184
  _globals['_INVALIDRANGEDETAIL']._serialized_end=347
  _globals['_TIMERANGEVALIDITY']._serialized_start=350
  _globals['_TIMERANGEVALIDITY']._serialized_end=509
# @@protoc_insertion_point(module_scope)
