# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VideoAnnotationV2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'VideoAnnotationV2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17VideoAnnotationV2.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\xba\x01\n\x0fSubSegmentsInfo\x12\x12\n\nsegment_id\x18\x01 \x01(\t\x12\x14\n\x0cstart_time_s\x18\x02 \x01(\x01\x12\x12\n\nend_time_s\x18\x03 \x01(\x01\x12\x12\n\nfine_label\x18\x04 \x01(\t\x12\x13\n\x0bstart_frame\x18\x05 \x01(\x05\x12\x11\n\tend_frame\x18\x06 \x01(\x05\x12\x12\n\nis_success\x18\x07 \x01(\x08\x12\x19\n\x11\x66ine_label_detail\x18\x08 \x01(\t\"\xe8\x01\n\x0cSegmentsInfo\x12\x12\n\nsegment_id\x18\x01 \x01(\t\x12\x14\n\x0cstart_time_s\x18\x02 \x01(\x01\x12\x12\n\nend_time_s\x18\x03 \x01(\x01\x12\x12\n\nfine_label\x18\x04 \x01(\t\x12\x13\n\x0bstart_frame\x18\x05 \x01(\x05\x12\x11\n\tend_frame\x18\x06 \x01(\x05\x12\x34\n\x11sub_segments_info\x18\x07 \x03(\x0b\x32\x19.foxglove.SubSegmentsInfo\x12\r\n\x05scene\x18\x08 \x01(\t\x12\x19\n\x11scene_description\x18\t \x01(\t\"\xc2\x01\n\x11VideoAnnotationV2\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x11\n\tbold_mark\x18\x02 \x01(\t\x12\x0b\n\x03sst\x18\x03 \x01(\t\x12-\n\rsegments_info\x18\x04 \x03(\x0b\x32\x16.foxglove.SegmentsInfo\x12+\n\x06header\x18\x05 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x1f\n\x17\x65nvironment_description\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VideoAnnotationV2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSEGMENTSINFO']._serialized_start=52
  _globals['_SUBSEGMENTSINFO']._serialized_end=238
  _globals['_SEGMENTSINFO']._serialized_start=241
  _globals['_SEGMENTSINFO']._serialized_end=473
  _globals['_VIDEOANNOTATIONV2']._serialized_start=476
  _globals['_VIDEOANNOTATIONV2']._serialized_end=670
# @@protoc_insertion_point(module_scope)
